name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: dist
          retention-days: 1

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: dist
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  notify:
    needs: [build, deploy]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
    steps:
      - name: Deployment Success
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ needs.deploy.result == 'success' }}
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: A new version of Phonebook deployed
          embed-description: to https://fullstackopen-phonebook-cicd-myuwi.fly.dev/ by ${{ github.event.head_commit.author.username }}
          embed-color: 2278750
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Build failure
        uses: tsickert/discord-webhook@v6.0.0
        if: ${{ failure() }}
        with:
          username: GitHub
          avatar-url: https://avatars.githubusercontent.com/u/9919
          embed-title: Build failed
          embed-description: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.author.username }} broke the build :(
          embed-color: 15680580
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
